file=open("Codingal.txt","r")
print(file.read())
file.close()
file=open("Codingal.txt","r")
print("\n Read In Parts \n")
print(file.read(12))
file.close()
file=open("Codingal.txt","a")
file.write("!!!!!!!!")
file.close()